// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk4B-eYiHX7-LSiTHP5CXgN9gBSDk3Yis',
    appId: '1:54700997246:web:1df6c85fe083141707f62f',
    messagingSenderId: '54700997246',
    projectId: 'newproject-aae3a',
    authDomain: 'newproject-aae3a.firebaseapp.com',
    storageBucket: 'newproject-aae3a.appspot.com',
    measurementId: 'G-24Z9VRKZ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0tsA0zV5Bynwmj3qo-3dmDfKfthexc2M',
    appId: '1:54700997246:android:384dd811d46fa34407f62f',
    messagingSenderId: '54700997246',
    projectId: 'newproject-aae3a',
    storageBucket: 'newproject-aae3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChfMfcfHbvkYJe3v91hDFbHPUvF4fOvKo',
    appId: '1:54700997246:ios:682b5e83e2a0dfe307f62f',
    messagingSenderId: '54700997246',
    projectId: 'newproject-aae3a',
    storageBucket: 'newproject-aae3a.appspot.com',
    iosClientId: '54700997246-7oisp97jjlkm03v4sa8j4ms4jqn5dnlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChfMfcfHbvkYJe3v91hDFbHPUvF4fOvKo',
    appId: '1:54700997246:ios:682b5e83e2a0dfe307f62f',
    messagingSenderId: '54700997246',
    projectId: 'newproject-aae3a',
    storageBucket: 'newproject-aae3a.appspot.com',
    iosClientId: '54700997246-7oisp97jjlkm03v4sa8j4ms4jqn5dnlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );
}
